pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  inputs:
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/restore'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    arguments: '--no-build --configuration=$(buildConfiguration)'
